Imports System.Resources
Imports System.Reflection
Imports System.Runtime.CompilerServices
Imports System.Runtime.InteropServices
Imports Microsoft.VisualBasic

' General Information about an assembly is controlled through the following 
' set of attributes. Change these attribute values to modify the information
' associated with an assembly.
<Assembly: AssemblyTitle("Auto Temp File Cleaner for Visual Studio 2022")>
<Assembly: AssemblyDescription("Automatically cleans up temporary files generated by Visual Studio when the IDE is closed.")>
<Assembly: AssemblyConfiguration("")>
<Assembly: AssemblyCompany("ElektroStudios")>
<Assembly: AssemblyProduct("Auto Temp File Cleaner for Visual Studio 2022")>
<Assembly: AssemblyCopyright("Copyright © ElektroStudios 2024")>
<Assembly: AssemblyTrademark("")>
<Assembly: AssemblyCulture("en-US")>

' Setting ComVisible to false makes the types in this assembly not visible 
' to COM components.  If you need to access a type in this assembly from 
' COM, set the ComVisible attribute to true on that type.
<Assembly: ComVisible(False)>

' Version information for an assembly consists of the following four values:
'
'      Major Version
'      Minor Version 
'      Build Number
'      Revision
'
' You can specify all the values or you can default the Build and Revision Numbers 
' by using the '*' as shown below:
' [assembly: AssemblyVersion("1.0.*")]
<Assembly: AssemblyVersion("1.1.0.0")>
<Assembly: AssemblyFileVersion("1.1.0.0")>
<Assembly: NeutralResourcesLanguage("en")>
<Assembly: Guid("f52e6d9f-8d57-4a20-a73c-fc0c3e1a4b81")>
